[package]
name = "custom_overlay_from_clipboard_content"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = { version = "3.5.0", features = ["wayland-data-control"] }
eframe = "0.31.1"
inputbot = "0.6.0"
str-distance = "0.1.0"
tts = "0.26.3"
