name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install libxtst-dev libx11-dev libxtst-dev libudev-dev libinput-dev
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
          path: target/release/custom_overlay_from_clipboard_content
